// Code generated by ModelQ
// face.go contains model for the database table [public.face]

package models

import (
	"database/sql"
	"encoding/gob"
	"encoding/json"
	"fmt"
	"github.com/mijia/modelq/gmq"
	"strings"
)

type Face struct {
	Id       int64 `json:"id"`
	PersonId int64 `json:"person_id"`
}

// Start of the Face APIs.

func (obj Face) String() string {
	if data, err := json.Marshal(obj); err != nil {
		return fmt.Sprintf("<Face Id=%v>", obj.Id)
	} else {
		return string(data)
	}
}

func (obj Face) Get(dbtx gmq.DbTx) (Face, error) {
	filter := FaceObjs.FilterId("=", obj.Id)
	if result, err := FaceObjs.Select().Where(filter).One(dbtx); err != nil {
		return obj, err
	} else {
		return result, nil
	}
}

func (obj Face) Insert(dbtx gmq.DbTx) (Face, error) {
	if result, err := FaceObjs.Insert(obj).Run(dbtx); err != nil {
		return obj, err
	} else {
		if dbtx.DriverName() != "postgres" {
			if id, err := result.LastInsertId(); err != nil {
				return obj, err
			} else {
				obj.Id = id
				return obj, err
			}
		}
		return obj, nil
	}
}

func (obj Face) Update(dbtx gmq.DbTx) (int64, error) {
	fields := []string{"PersonId"}
	filter := FaceObjs.FilterId("=", obj.Id)
	if result, err := FaceObjs.Update(obj, fields...).Where(filter).Run(dbtx); err != nil {
		return 0, err
	} else {
		return result.RowsAffected()
	}
}

func (obj Face) Delete(dbtx gmq.DbTx) (int64, error) {
	filter := FaceObjs.FilterId("=", obj.Id)
	if result, err := FaceObjs.Delete().Where(filter).Run(dbtx); err != nil {
		return 0, err
	} else {
		return result.RowsAffected()
	}
}

// Start of the inner Query Api

type _FaceQuery struct {
	gmq.Query
}

func (q _FaceQuery) Where(f gmq.Filter) _FaceQuery {
	q.Query = q.Query.Where(f)
	return q
}

func (q _FaceQuery) OrderBy(by ...string) _FaceQuery {
	tBy := make([]string, 0, len(by))
	for _, b := range by {
		sortDir := ""
		if b[0] == '-' || b[0] == '+' {
			sortDir = string(b[0])
			b = b[1:]
		}
		if col, ok := FaceObjs.fcMap[b]; ok {
			tBy = append(tBy, sortDir+col)
		}
	}
	q.Query = q.Query.OrderBy(tBy...)
	return q
}

func (q _FaceQuery) GroupBy(by ...string) _FaceQuery {
	tBy := make([]string, 0, len(by))
	for _, b := range by {
		if col, ok := FaceObjs.fcMap[b]; ok {
			tBy = append(tBy, col)
		}
	}
	q.Query = q.Query.GroupBy(tBy...)
	return q
}

func (q _FaceQuery) Limit(offsets ...int64) _FaceQuery {
	q.Query = q.Query.Limit(offsets...)
	return q
}

func (q _FaceQuery) Page(number, size int) _FaceQuery {
	q.Query = q.Query.Page(number, size)
	return q
}

func (q _FaceQuery) Run(dbtx gmq.DbTx) (sql.Result, error) {
	return q.Query.Exec(dbtx)
}

type FaceRowVisitor func(obj Face) bool

func (q _FaceQuery) Iterate(dbtx gmq.DbTx, functor FaceRowVisitor) error {
	return q.Query.SelectList(dbtx, func(columns []gmq.Column, rb []sql.RawBytes) bool {
		obj := FaceObjs.toFace(columns, rb)
		return functor(obj)
	})
}

func (q _FaceQuery) One(dbtx gmq.DbTx) (Face, error) {
	var obj Face
	err := q.Query.SelectOne(dbtx, func(columns []gmq.Column, rb []sql.RawBytes) bool {
		obj = FaceObjs.toFace(columns, rb)
		return true
	})
	return obj, err
}

func (q _FaceQuery) List(dbtx gmq.DbTx) ([]Face, error) {
	result := make([]Face, 0, 10)
	err := q.Query.SelectList(dbtx, func(columns []gmq.Column, rb []sql.RawBytes) bool {
		obj := FaceObjs.toFace(columns, rb)
		result = append(result, obj)
		return true
	})
	return result, err
}

// Start of the model facade Apis.

type _FaceObjs struct {
	fcMap map[string]string
}

func (o _FaceObjs) Names() (schema, tbl, alias string) {
	return "public", "face", "Face"
}

func (o _FaceObjs) Select(fields ...string) _FaceQuery {
	q := _FaceQuery{}
	if len(fields) == 0 {
		fields = []string{"Id", "PersonId"}
	}
	q.Query = gmq.Select(o, o.columns(fields...))
	return q
}

func (o _FaceObjs) Insert(obj Face) _FaceQuery {
	q := _FaceQuery{}
	q.Query = gmq.Insert(o, o.columnsWithData(obj, "PersonId"))
	return q
}

func (o _FaceObjs) Update(obj Face, fields ...string) _FaceQuery {
	q := _FaceQuery{}
	q.Query = gmq.Update(o, o.columnsWithData(obj, fields...))
	return q
}

func (o _FaceObjs) Delete() _FaceQuery {
	q := _FaceQuery{}
	q.Query = gmq.Delete(o)
	return q
}

///// Managed Objects Filters definition

func (o _FaceObjs) FilterId(op string, p int64, ps ...int64) gmq.Filter {
	params := make([]interface{}, 1+len(ps))
	params[0] = p
	for i := range ps {
		params[i+1] = ps[i]
	}
	return o.newFilter("id", op, params...)
}

func (o _FaceObjs) FilterPersonId(op string, p int64, ps ...int64) gmq.Filter {
	params := make([]interface{}, 1+len(ps))
	params[0] = p
	for i := range ps {
		params[i+1] = ps[i]
	}
	return o.newFilter("person_id", op, params...)
}

///// Managed Objects Columns definition

func (o _FaceObjs) ColumnId(p ...int64) gmq.Column {
	var value interface{}
	if len(p) > 0 {
		value = p[0]
	}
	return gmq.Column{"id", value}
}

func (o _FaceObjs) ColumnPersonId(p ...int64) gmq.Column {
	var value interface{}
	if len(p) > 0 {
		value = p[0]
	}
	return gmq.Column{"person_id", value}
}

////// Internal helper funcs

func (o _FaceObjs) newFilter(name, op string, params ...interface{}) gmq.Filter {
	if strings.ToUpper(op) == "IN" {
		return gmq.InFilter(name, params)
	}
	return gmq.UnitFilter(name, op, params[0])
}

func (o _FaceObjs) toFace(columns []gmq.Column, rb []sql.RawBytes) Face {
	obj := Face{}
	if len(columns) == len(rb) {
		for i := range columns {
			switch columns[i].Name {
			case "id":
				obj.Id = gmq.AsInt64(rb[i])
			case "person_id":
				obj.PersonId = gmq.AsInt64(rb[i])
			}
		}
	}
	return obj
}

func (o _FaceObjs) columns(fields ...string) []gmq.Column {
	data := make([]gmq.Column, 0, len(fields))
	for _, f := range fields {
		switch f {
		case "Id":
			data = append(data, o.ColumnId())
		case "PersonId":
			data = append(data, o.ColumnPersonId())
		}
	}
	return data
}

func (o _FaceObjs) columnsWithData(obj Face, fields ...string) []gmq.Column {
	data := make([]gmq.Column, 0, len(fields))
	for _, f := range fields {
		switch f {
		case "Id":
			data = append(data, o.ColumnId(obj.Id))
		case "PersonId":
			data = append(data, o.ColumnPersonId(obj.PersonId))
		}
	}
	return data
}

var FaceObjs _FaceObjs

func init() {
	FaceObjs.fcMap = map[string]string{
		"Id":       "id",
		"PersonId": "person_id",
	}
	gob.Register(Face{})
}
